apiVersion: v1
kind: Service
metadata:
  name: {{ include "aes-api.name" . }}-api
  labels:
    app: {{ include "aes-api.name" . }}-api
    {{- include "aes-api.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: {{ include "aes-api.name" . }}-api
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: http
      nodePort: {{ .Values.api.nodePort }}
