apiVersion: v1
kind: Service
metadata:
  name: {{ include "aes-api.name" . }}-worker
  labels:
    app: {{ include "aes-api.name" . }}-worker
    {{- include "aes-api.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app: {{ include "aes-api.name" . }}-worker
  ports:
    - name: metrics
      port: {{ .Values.worker.metricsPort }}
      targetPort: metrics
