"""Add traceability to correction attempts and submissions.

Revision ID: cf7a2a2e8d11
Revises: a7c2e9f41b58
Create Date: 2026-09-19 18:40:27.113830
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cf7a2a2e8d11"
down_revision: str | Sequence[str] | None = "a7c2e9f41b58"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("correction_attempts", sa.Column("cache_read_tokens", sa.Integer(), nullable=True))
    op.add_column("correction_attempts", sa.Column("cache_write_tokens", sa.Integer(), nullable=True))
    op.add_column("correction_attempts", sa.Column("cost_usd", sa.Numeric(precision=12, scale=8), nullable=True))
    op.add_column("correction_attempts", sa.Column("served_provider", sa.String(length=100), nullable=True))
    op.add_column("correction_attempts", sa.Column("guardrail_events", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("correction_attempts", sa.Column("model_retries", sa.Integer(), nullable=True))
    op.add_column("submissions", sa.Column("transcription_meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("submissions", "transcription_meta")
    op.drop_column("correction_attempts", "model_retries")
    op.drop_column("correction_attempts", "guardrail_events")
    op.drop_column("correction_attempts", "served_provider")
    op.drop_column("correction_attempts", "cost_usd")
    op.drop_column("correction_attempts", "cache_write_tokens")
    op.drop_column("correction_attempts", "cache_read_tokens")
    # ### end Alembic commands ###
